Repository Zeckie/ProxyAuth, pull requests merged in 2021-11, with the labels that each got.

#15 fix the build workflow to upload the release asset
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: hacktoberfest-accepted

#11 Keep a changelog
  .github/workflows/build.yml
  .github/workflows/release.yml
  CHANGELOG.md
  build.gradle.kts
Labels: hacktoberfest-accepted

#25 Configuration
  CHANGELOG.md
  build.gradle.kts
  src/main/java/proxyauth/Configuration.java
  src/main/java/proxyauth/Main.java
  src/main/java/proxyauth/PassThrough.java
  src/main/java/proxyauth/ProxyListener.java
  src/main/java/proxyauth/ProxyRequest.java
  src/main/java/proxyauth/StatusListener.java
  src/main/java/proxyauth/Utils.java
  src/main/java/proxyauth/actions/Action.java
  src/main/java/proxyauth/actions/CloseAction.java
  src/main/java/proxyauth/actions/EchoAction.java
  src/main/java/proxyauth/actions/ForwardAction.java
  src/main/java/proxyauth/actions/ForwardRequest.java
  src/main/java/proxyauth/conf/Configuration.java
  src/main/java/proxyauth/conf/Converter.java
  src/main/java/proxyauth/conf/Setting.java
  src/main/resources/proxyauth/LICENSE
  src/test/java/proxyauth/conf/TestSetting.java
Labels: enhancement

#26 Close connection instead of keep-alive
  build.gradle.kts
  src/main/java/proxyauth/PassThrough.java
  src/main/java/proxyauth/ProxyListener.java
  src/main/java/proxyauth/actions/ForwardRequest.java
  src/main/java/proxyauth/conf/Configuration.java
  src/test/java/proxyauth/End2End.java
  src/test/java/proxyauth/conf/TestConfiguration.java
Labels: bug
